# Generated by Django 4.1.7 on 2023-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=200)),
                ('search_term', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
