# Generated by Django 4.1.7 on 2023-02-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_search_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='email',
        ),
        migrations.AddField(
            model_name='search',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
